#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, urllib, re

cname = {
    "TWD": "新台幣", "CNY": "人民幣", "JPY": "日圓", "KRW": "韓圜",
    "HKD": "港幣", "THB": "泰銖", "SGD": "新加坡幣", "IDR": "印尼盾",
    "VND": "越南幣", "MYR": "馬來西亞幣", "PHP": "菲律賓披索", "INR": "印度幣",
    "AED": "阿拉伯幣", "KWD": "科威特幣", "AUD": "澳幣", "NZD": "紐西蘭幣",
    "USD": "美元", "CAD": "加拿大幣", "BRL": "巴西幣", "MXN": "墨西哥披索",
    "ARS": "阿根廷披索", "CLP": "智利披索", "VEB": "委內瑞拉幣", "EUR": "歐元",
    "GBP": "英鎊", "RUB": "俄羅斯盧比", "CHF": "瑞士法郎", "SEK": "瑞典克朗",
    "ZAR": "南非幣",
}

coin = [
    "TWD", "CNY", "JPY", "KRW",
    "HKD", "THB", "SGD", "IDR",
    "VND", "MYR", "PHP", "INR",
    "AED", "KWD", "AUD", "NZD",
    "USD", "CAD", "BRL", "MXN",
    "ARS", "CLP", "VEB", "EUR",
    "GBP", "RUB", "CHF", "SEK",
    "ZAR"
]

calias = {
    "NTD": "TWD", "RMB": "CNY"
}

def get_ex_money(money, fr, to="TWD"):
    if fr == to:
        return "你在開我玩笑嗎？"
    
    url = "http://tw.money.yahoo.com/currency_exc_result?amt=%s&from=%s&to=%s" % (money, fr, to)
    data = urllib.urlopen(url).read()
    l = re.findall("經過計算後， (.+)<div", data)
    if l:
        s = re.sub('</?em>', '', l[0])
        return s
    else:
        return ''
    
def expand_alias(alias):
    if calias.has_key(alias):
        return calias[alias]
    return alias

def help():
    print '使用方法: "10 USD to NTD", 或是只輸入 "10 USD"'

def clist():
    result = "".join(["%s(%s), " % (cname[k], k) for k in cname.keys()])
    result = result[:-2] # strip last 2 char
    s = "以下是可以轉換的匯率: " + result
    print s

read_stdin = False

if len(sys.argv) <= 1:
    help()
    sys.exit(0)
if sys.argv[1] == "help" or sys.argv[1] == "-h" or sys.argv[1] == "--help":
    help()
    sys.exit(0)
elif sys.argv[1] == "list" or sys.argv[1] == "-l" or sys.argv[1] == "--list":
    clist()
    sys.exit(0)
elif sys.argv[1] == "-s":
    read_stdin = True
    
coins = "|".join(coin) + "|" + "|".join(calias)
if read_stdin == False:
    text = " ".join(sys.argv[1:])
else:
    text = sys.stdin.readline()

m = re.search("^([\d\.\+\-\*\/]+)\s*(%s)$" % coins, text, re.I)
reply = "抱歉"
if m:
    reply = get_ex_money(m.group(1), expand_alias(m.group(2).upper()))
else:
    m = re.search("^([\d\.\+\-\*\/]+)\s*(%s)\s+to\s+(%s)$" % (coins, coins), text, re.I)
    if m:
        reply = get_ex_money(m.group(1), expand_alias(m.group(2).upper()), expand_alias(m.group(3).upper()))

print reply

